# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: "@dod-advana/advana-jira-feedback"

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: '@dod-advana'
      - run: |
          npm set "@dod-advana:registry" "https://npm.pkg.github.com" && \
          npm set "//https://npm.pkg.github.com/:_authToken" "${NODE_AUTH_TOKEN}" && \
          npm install && npm ci && npm test --passWithNoTests
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMRC_FILE}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - run: |
          npm set "@dod-advana:registry" "https://npm.pkg.github.com" && \
          npm set "//https://npm.pkg.github.com/:_authToken" "${NODE_AUTH_TOKEN}" && \
          npm install && npm ci
      - run: npm run publish:prepare
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMRC_FILE}}
